### ISSUE TITLE
Use user's theme by default instead of Solarized (Light)

### ISSUE THREAD

**Issue by kristerkari** [mazurov/sublime-levels#10]
First of all, thanks for the plugin :+1: 

I would like the plugin to use the theme that the user has defined in the ST settings by default. Currently I have to go and manually add the theme I want Levels to use instead of Solarized (Light).

**Comment by mazurov** [comment]
Default scope colors could look ugly in your favorite theme. But you can  [add](https://github.com/mazurov/sublime-levels#theme-customization) scope colors definition to your theme and update Levels plugin settings: `"color_scheme": "Packages/Path-to-Your.tmTheme"`

**Comment by kristerkari** [comment]
Yes ,I know that the colors might look ugly, but still IMO defining all the colors manually, adding them to the current theme and changing the plugin settings is something that almost no one is going to want to do.

**Comment by kristerkari** [comment]
...and I'm not against being able to customize the colors, I just think that using Solarized (Light) is not a good default unless the user is already using it.

**Comment by mazurov** [comment]
:thought_balloon:I will think on this issue  

:paperclip:  You can use  Solarized (Dark) by changing plugin settings:
`"color_scheme": "Packages/{{levels_plugin_name}}/Levels-dark.hidden-tmTheme",`

**Comment by ryanblakeley** [comment]
Is there a way to set up a theme that colors the text and not the background behind the text?
