### ISSUE TITLE
"catch" in try/catch is (incorrectly?) being hilighted as scope variable

### ISSUE THREAD

**Issue by bwiklund** [mazurov/sublime-levels#13]

**Comment by mazurov** [comment]
Hi Ben, could you attach a screenshot with your problem?

**Comment by bwiklund** [comment]
Sure thing: http://i.imgur.com/1O9eqzr.png

**Comment by mazurov** [comment]
It's not the bug. By design, the eslevels hightlights not only the variables, but also the keywords that introduce new variable scopes, such as `function`, `catch`. In your case `catch` creates a new variable scope with variable `e` inside.

**Comment by bwiklund** [comment]
Hmm, makes sense. TY!
